/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.ControllerPaneles;
import Controller.ControllerValidation;
import Controller.ControllerViewClientes;
import Controller.ControllerViewSession;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Carolina
 */
public class ViewAgregarCliente extends javax.swing.JPanel {
    ControllerValidation validation;
    ControllerPaneles controllerPaneles;
    ControllerViewClientes controller;

    /**
     * Creates new form ViewAgregarCliente
     * @param controllerPaneles
     */
    public ViewAgregarCliente(ControllerPaneles controllerPaneles) {
        initComponents();
        this.controllerPaneles = controllerPaneles;//asi
        this.validation = new ControllerValidation();
        this.validationClientes();
        
    }

    public void validationClientes()
    {
        ArrayList components = new ArrayList<>();
        components.add(Nombre);
        components.add (acApellidoPaterno);
        components.add (acApellidoMaterno);
        components.add (acRFC);
        components.add (acTelefono);
        components.add (acTelCelular);
        components.add (acEmail);
        components.add (acCalle);
        components.add (acCiudad);
        components.add (acColonia);
        components.add (acEstados);
        components.add (acCP);
        components.add (acNoExt);
        components.add (acNoInt);
        
        controller = new ControllerViewClientes(components);
        controller.validations();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        acApellidoPaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        acApellidoMaterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        acRFC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        acTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        acTelCelular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        acEmail = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        acCalle = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        acNoExt = new javax.swing.JTextField();
        acNoInt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        acColonia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        acCiudad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        acCP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        acEstados = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        acIdCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 246, 247));
        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(120, 120, 120), 1, true));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre: ");

        Nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(180, 180, 180));
        Nombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre.setText("Nombre");
        Nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NombreFocusLost(evt);
            }
        });
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Apellido Paterno:");

        acApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acApellidoPaterno.setForeground(new java.awt.Color(180, 180, 180));
        acApellidoPaterno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        acApellidoPaterno.setText("Apellido Paterno");
        acApellidoPaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acApellidoPaternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                acApellidoPaternoFocusLost(evt);
            }
        });
        acApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acApellidoPaternoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Apellido Materno:");

        acApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acApellidoMaterno.setForeground(new java.awt.Color(180, 180, 180));
        acApellidoMaterno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        acApellidoMaterno.setText("Apellido Materno");
        acApellidoMaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acApellidoMaternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                acApellidoMaternoFocusLost(evt);
            }
        });
        acApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acApellidoMaternoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("RFC:");

        acRFC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acRFC.setForeground(new java.awt.Color(180, 180, 180));
        acRFC.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        acRFC.setText("RFC");
        acRFC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acRFCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                acRFCFocusLost(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Email:");

        acTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acTelefono.setForeground(new java.awt.Color(180, 180, 180));
        acTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        acTelefono.setText("xx-xxx-xxxxxxx");
        acTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                acTelefonoFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Teléfono:");

        acTelCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acTelCelular.setForeground(new java.awt.Color(180, 180, 180));
        acTelCelular.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        acTelCelular.setText("xx-xxx-xxxxxxx");
        acTelCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acTelCelularFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                acTelCelularFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tel. Celular:");

        acEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acEmail.setForeground(new java.awt.Color(180, 180, 180));
        acEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        acEmail.setText("cliente@reposteria.com");
        acEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                acEmailFocusLost(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Calle:");

        acCalle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acCalle.setForeground(new java.awt.Color(180, 180, 180));
        acCalle.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        acCalle.setText("Calle");
        acCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acCalleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                acCalleFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("No. Ext:");

        acNoExt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acNoExt.setForeground(new java.awt.Color(180, 180, 180));
        acNoExt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        acNoExt.setText("No. Ext.");
        acNoExt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acNoExtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                acNoExtFocusLost(evt);
            }
        });
        acNoExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acNoExtActionPerformed(evt);
            }
        });

        acNoInt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acNoInt.setForeground(new java.awt.Color(180, 180, 180));
        acNoInt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        acNoInt.setText("No. Int");
        acNoInt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acNoIntFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                acNoIntFocusLost(evt);
            }
        });
        acNoInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acNoIntActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Colonia:");

        acColonia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acColonia.setForeground(new java.awt.Color(180, 180, 180));
        acColonia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        acColonia.setText("Colonia");
        acColonia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acColoniaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                acColoniaFocusLost(evt);
            }
        });
        acColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acColoniaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Ciudad:");

        acCiudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acCiudad.setForeground(new java.awt.Color(180, 180, 180));
        acCiudad.setText("Ciudad");
        acCiudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acCiudadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                acCiudadFocusLost(evt);
            }
        });
        acCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acCiudadActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("C.P:");

        acCP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acCP.setForeground(new java.awt.Color(180, 180, 180));
        acCP.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        acCP.setText("xxxxx");
        acCP.setToolTipText("");
        acCP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acCPFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Estado:");

        acEstados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acEstados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Coahuila", "Colima", "Distrito Federal", "Durango", "Estado de México", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas" }));
        acEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acEstadosActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("No. Int");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(66, 139, 202));
        jLabel18.setText("Dirección");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(291, 291, 291)
                                    .addComponent(acNoExt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(acCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(acColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acNoInt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(acCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(acCP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(241, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(acCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(acNoExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(acNoInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(acCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(acEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)))
        );

        acIdCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acIdCliente.setForeground(new java.awt.Color(180, 180, 180));
        acIdCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        acIdCliente.setText("Id Cliente");
        acIdCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acIdClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                acIdClienteFocusLost(evt);
            }
        });
        acIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acIdClienteActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPreferredSize(new java.awt.Dimension(107, 33));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tick-outline.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/times-outline.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(66, 139, 202));
        jLabel16.setText("Información personal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(acApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(acApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(acIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(acRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel16))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(26, 26, 26))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(acIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(acApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(acApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel20.setBackground(new java.awt.Color(250, 250, 250));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/usuarioInfo.png"))); // NOI18N
        jLabel20.setText("Agregar un cliente nuevo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acIdClienteActionPerformed

    private void acIdClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acIdClienteFocusGained
        validation.placeHolder(true,acIdCliente,"Id Cliente"); // TODO add your handling code here:
    }//GEN-LAST:event_acIdClienteFocusGained

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void acIdClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acIdClienteFocusLost
        validation.placeHolder(false,acIdCliente,"Id Cliente");// TODO add your handling code here:
    }//GEN-LAST:event_acIdClienteFocusLost

    private void NombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreFocusGained
        validation.placeHolder(true,Nombre,"Nombre");        // TODO add your handling code here:
    }//GEN-LAST:event_NombreFocusGained

    private void NombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreFocusLost
        validation.placeHolder(false,Nombre,"Nombre");         // TODO add your handling code here:
    }//GEN-LAST:event_NombreFocusLost

    private void acApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acApellidoPaternoActionPerformed

    private void acApellidoPaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acApellidoPaternoFocusGained
        validation.placeHolder(true,acApellidoPaterno,"Apellido Paterno");        // TODO add your handling code here:
    }//GEN-LAST:event_acApellidoPaternoFocusGained

    private void acApellidoPaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acApellidoPaternoFocusLost
       validation.placeHolder(false, acApellidoPaterno,"Apellido Paterno"); // TODO add your handling code here:
    }//GEN-LAST:event_acApellidoPaternoFocusLost

    private void acApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acApellidoMaternoActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_acApellidoMaternoActionPerformed

    private void acApellidoMaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acApellidoMaternoFocusGained
        validation.placeHolder(true,acApellidoMaterno,"Apellido Materno");        // TODO add your handling code here:
    }//GEN-LAST:event_acApellidoMaternoFocusGained

    private void acApellidoMaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acApellidoMaternoFocusLost
        validation.placeHolder(false,acApellidoMaterno,"Apellido Materno");        // TODO add your handling code here:
    }//GEN-LAST:event_acApellidoMaternoFocusLost

    private void acRFCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acRFCFocusGained
        validation.placeHolder(true,acRFC,"RFC");        // TODO add your handling code here:
    }//GEN-LAST:event_acRFCFocusGained

    private void acRFCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acRFCFocusLost
        validation.placeHolder(false,acRFC,"RFC");        // TODO add your handling code here:
    }//GEN-LAST:event_acRFCFocusLost

    private void acTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acTelefonoFocusGained
        validation.placeHolder(true,acTelefono,"xx-xxx-xxxxxxx");        // TODO add your handling code here:
    }//GEN-LAST:event_acTelefonoFocusGained

    private void acTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acTelefonoFocusLost
        validation.placeHolder(false,acTelefono,"xx-xxx-xxxxxxx");        // TODO add your handling code here:
    }//GEN-LAST:event_acTelefonoFocusLost

    private void acTelCelularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acTelCelularFocusGained
        validation.placeHolder(true,acTelCelular,"xx-xxx-xxxxxxx");        // TODO add your handling code here:
    }//GEN-LAST:event_acTelCelularFocusGained

    private void acTelCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acTelCelularFocusLost
        validation.placeHolder(false,acTelCelular,"xx-xxx-xxxxxxx");        // TODO add your handling code here:
    }//GEN-LAST:event_acTelCelularFocusLost

    private void acEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acEmailFocusGained
        validation.placeHolder(true,acEmail,"cliente@reposteria.com");        // TODO add your handling code here:
    }//GEN-LAST:event_acEmailFocusGained

    private void acEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acEmailFocusLost
        validation.placeHolder(false,acEmail,"cliente@reposteria.com");        // TODO add your handling code here:
    }//GEN-LAST:event_acEmailFocusLost

    private void acCalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acCalleFocusGained
        validation.placeHolder(true,acCalle,"Calle");        // TODO add your handling code here:
    }//GEN-LAST:event_acCalleFocusGained

    private void acCalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acCalleFocusLost
        validation.placeHolder(false,acCalle,"Calle");        // TODO add your handling code here:
    }//GEN-LAST:event_acCalleFocusLost

    private void acNoExtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acNoExtFocusGained
        validation.placeHolder(true,acNoExt,"No. Ext.");        // TODO add your handling code here:
    }//GEN-LAST:event_acNoExtFocusGained

    private void acNoExtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acNoExtFocusLost
        validation.placeHolder(false,acNoExt,"No. Ext.");        // TODO add your handling code here:
    }//GEN-LAST:event_acNoExtFocusLost

    private void acNoIntFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acNoIntFocusGained
        validation.placeHolder(true,acNoInt,"No. Int");       // TODO add your handling code here:
    }//GEN-LAST:event_acNoIntFocusGained

    private void acNoIntFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acNoIntFocusLost
        validation.placeHolder(false,acNoInt,"No. Int");        // TODO add your handling code here:
    }//GEN-LAST:event_acNoIntFocusLost

    private void acColoniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acColoniaFocusGained
        validation.placeHolder(true,acColonia,"Colonia");        // TODO add your handling code here:
    }//GEN-LAST:event_acColoniaFocusGained

    private void acColoniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acColoniaFocusLost
        validation.placeHolder(false,acColonia,"Colonia");        // TODO add your handling code here:
    }//GEN-LAST:event_acColoniaFocusLost

    private void acCiudadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acCiudadFocusGained
        validation.placeHolder(true,acCiudad,"Ciudad");        // TODO add your handling code here:
    }//GEN-LAST:event_acCiudadFocusGained

    private void acCiudadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acCiudadFocusLost
        validation.placeHolder(false,acCiudad,"Ciudad");        // TODO add your handling code here:
    }//GEN-LAST:event_acCiudadFocusLost

    private void acCPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acCPFocusGained
        validation.placeHolder(true,acCP,"xxxxx");        // TODO add your handling code here:
    }//GEN-LAST:event_acCPFocusGained

    private void acCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acCiudadActionPerformed

    private void acColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acColoniaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       controllerPaneles.addPanel(controllerPaneles.getPanelCentral(), new ViewClientes(controllerPaneles)); //asi
    }//GEN-LAST:event_jButton2ActionPerformed

    private void acEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acEstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acEstadosActionPerformed

    private void acNoExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acNoExtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acNoExtActionPerformed

    private void acNoIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acNoIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acNoIntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField acApellidoMaterno;
    private javax.swing.JTextField acApellidoPaterno;
    private javax.swing.JTextField acCP;
    private javax.swing.JTextField acCalle;
    private javax.swing.JTextField acCiudad;
    private javax.swing.JTextField acColonia;
    private javax.swing.JTextField acEmail;
    private javax.swing.JComboBox acEstados;
    private javax.swing.JTextField acIdCliente;
    private javax.swing.JTextField acNoExt;
    private javax.swing.JTextField acNoInt;
    private javax.swing.JTextField acRFC;
    private javax.swing.JTextField acTelCelular;
    private javax.swing.JTextField acTelefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
