/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerPaneles;
import Controller.ControllerValidation;
import Controller.ControllerViewVendedor;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Teté
 */
public class ViewRealizarVentas extends javax.swing.JPanel {
    ControllerValidation validation;
    ControllerViewVendedor controller;
    ControllerPaneles controllerPaneles;

    /**
     * Creates new form ViewCaptInfVendedor
     * @param controllerPaneles
     */
    public ViewRealizarVentas(ControllerPaneles controllerPaneles /*,ModeloPedidos ped */) {
        this.controllerPaneles = controllerPaneles;
        this.validation = new ControllerValidation();
        //this.controllerPaneles = controllerPaneles;
        initComponents();
        validation();
    }
//
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void validation(){
        ArrayList components = new ArrayList<>();
//        components.add(idCliente);
//        components.add(tipoVenta);
//        components.add(fecha);
//        components.add(horaEnt);
//        components.add(lugarEnt);
//        components.add(idVentas);
//        components.add(codBarras);
//        components.add(descripcion);
//        components.add(price);
//        components.add(cantidad);
//        components.add(descuento);
//        components.add(importe);
//        components.add(abono);
//        components.add(resto);
//        components.add(subtotal);
//        components.add(iva);
//        components.add(totalT);
//        controller = new ControllerViewVendedor(components);
//        controller.validations();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonFechaVen1 = new javax.swing.JButton();
        panelCapInfVendedor = new javax.swing.JPanel();
        Fecha = new javax.swing.JPanel();
        labelNombreVenta = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        tipoVenta = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        cliente = new javax.swing.JComboBox();
        labelFecEnt = new javax.swing.JLabel();
        fechaEntrega = new com.toedter.calendar.JDateChooser();
        labelLugEnt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idVenta = new javax.swing.JLabel();
        idVentas = new javax.swing.JTextField();
        hora2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        hora1 = new javax.swing.JTextField();
        hora3 = new javax.swing.JComboBox();
        lugarEntrega = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idProducto = new javax.swing.JTextField();
        panelProducto = new javax.swing.JPanel();
        labelDescripcion = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        labelprecio = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        $ = new javax.swing.JLabel();
        labelcantidad = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        labelDcto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lableImporte = new javax.swing.JLabel();
        importe = new javax.swing.JTextField();
        botonAgregar = new javax.swing.JButton();
        incrementoVenta = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVendedor = new javax.swing.JTable();
        panelTotal = new javax.swing.JPanel();
        labelSub = new javax.swing.JLabel();
        subtotal = new javax.swing.JTextField();
        labelPrecioT = new javax.swing.JLabel();
        iva = new javax.swing.JTextField();
        totalT = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        botonAgregar1 = new javax.swing.JButton();
        labelPrecioT1 = new javax.swing.JLabel();
        abono = new javax.swing.JTextField();
        resto = new javax.swing.JTextField();
        labelResto = new javax.swing.JLabel();
        labelAbono = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        labelNuevaVenta = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        botonFechaVen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/calender.png"))); // NOI18N

        setBackground(new java.awt.Color(245, 246, 247));
        setPreferredSize(new java.awt.Dimension(900, 600));

        panelCapInfVendedor.setBackground(new java.awt.Color(245, 246, 247));
        panelCapInfVendedor.setOpaque(false);
        panelCapInfVendedor.setPreferredSize(new java.awt.Dimension(900, 600));

        Fecha.setBackground(new java.awt.Color(255, 255, 255));
        Fecha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));

        labelNombreVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombreVenta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNombreVenta.setText("Tipo Venta:");

        labelFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelFecha.setText("Fecha");

        tipoVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoVenta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mostrador", "Pedido" }));
        tipoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoVentaActionPerformed(evt);
            }
        });
        tipoVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tipoVentaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tipoVentaFocusLost(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("Cliente:");

        cliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona cliente" }));
        cliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                clienteFocusLost(evt);
            }
        });
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });

        labelFecEnt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelFecEnt.setText("Fecha de entrega:");

        fechaEntrega.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelLugEnt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelLugEnt.setText("Lugar de entrega:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Hora de entrega");

        idVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idVenta.setText("Código venta");

        idVentas.setEditable(false);
        idVentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idVentas.setForeground(new java.awt.Color(204, 204, 255));
        idVentas.setText("Cod. Venta");

        hora2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hora2.setForeground(new java.awt.Color(180, 180, 180));
        hora2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        hora2.setText("00");
        hora2.setPreferredSize(new java.awt.Dimension(49, 28));
        hora2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hora2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hora2FocusLost(evt);
            }
        });
        hora2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora2ActionPerformed(evt);
            }
        });
        hora2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hora2KeyPressed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(66, 139, 202));
        jLabel31.setText(":");

        hora1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hora1.setForeground(new java.awt.Color(180, 180, 180));
        hora1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hora1.setText("00");
        hora1.setPreferredSize(new java.awt.Dimension(49, 28));
        hora1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hora1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hora1FocusLost(evt);
            }
        });
        hora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora1ActionPerformed(evt);
            }
        });
        hora1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hora1KeyPressed(evt);
            }
        });

        hora3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hora3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM" }));
        hora3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hora3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hora3FocusLost(evt);
            }
        });
        hora3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora3ActionPerformed(evt);
            }
        });

        lugarEntrega.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lugarEntrega.setForeground(new java.awt.Color(180, 180, 180));
        lugarEntrega.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lugarEntrega.setText("Lugar de entregrega");
        lugarEntrega.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lugarEntregaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lugarEntregaFocusLost(evt);
            }
        });
        lugarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugarEntregaActionPerformed(evt);
            }
        });
        lugarEntrega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lugarEntregaKeyPressed(evt);
            }
        });

        fecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fecha.setForeground(new java.awt.Color(180, 180, 180));
        fecha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fecha.setText("Fecha del dia");
        fecha.setPreferredSize(new java.awt.Dimension(49, 28));
        fecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fechaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fechaFocusLost(evt);
            }
        });
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fechaKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código:");

        idProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idProducto.setForeground(new java.awt.Color(180, 180, 180));
        idProducto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        idProducto.setText("Código de barras");
        idProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idProductoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idProductoFocusLost(evt);
            }
        });
        idProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProductoActionPerformed(evt);
            }
        });
        idProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idProductoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout FechaLayout = new javax.swing.GroupLayout(Fecha);
        Fecha.setLayout(FechaLayout);
        FechaLayout.setHorizontalGroup(
            FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FechaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelNombreVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoVenta, 0, 200, Short.MAX_VALUE)
                    .addComponent(idProducto))
                .addGap(7, 7, 7)
                .addGroup(FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FechaLayout.createSequentialGroup()
                        .addComponent(labelFecEnt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hora1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hora2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hora3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(FechaLayout.createSequentialGroup()
                        .addGroup(FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelLugEnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FechaLayout.createSequentialGroup()
                                .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idVenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lugarEntrega))))
                .addContainerGap())
        );
        FechaLayout.setVerticalGroup(
            FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FechaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FechaLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombreVenta)
                            .addComponent(tipoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelLugEnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lugarEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FechaLayout.createSequentialGroup()
                        .addGroup(FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idVenta)
                            .addComponent(idVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)
                            .addComponent(jLabel1)
                            .addComponent(idProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelFecEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hora1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31)
                        .addComponent(hora2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hora3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        panelProducto.setBackground(new java.awt.Color(255, 255, 255));
        panelProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));

        labelDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDescripcion.setText("Descripción");

        descripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descripcion.setForeground(new java.awt.Color(180, 180, 180));
        descripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        descripcion.setText("Descripción");
        descripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descripcionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descripcionFocusLost(evt);
            }
        });
        descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionActionPerformed(evt);
            }
        });
        descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descripcionKeyPressed(evt);
            }
        });

        labelprecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelprecio.setText("Precio");

        price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        price.setForeground(new java.awt.Color(180, 180, 180));
        price.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        price.setText("Precio");
        price.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                priceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                priceFocusLost(evt);
            }
        });
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceKeyPressed(evt);
            }
        });

        $.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        $.setText("$");

        labelcantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelcantidad.setText("Cant.");

        cantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cantidad.setForeground(new java.awt.Color(180, 180, 180));
        cantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cantidad.setText("0");
        cantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidadFocusLost(evt);
            }
        });
        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadKeyPressed(evt);
            }
        });

        labelDcto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDcto.setText("Dcto.");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("%");

        lableImporte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lableImporte.setText("Importe $:");

        importe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        importe.setForeground(new java.awt.Color(180, 180, 180));
        importe.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        importe.setText("0");
        importe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                importeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                importeFocusLost(evt);
            }
        });
        importe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importeActionPerformed(evt);
            }
        });
        importe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                importeKeyPressed(evt);
            }
        });

        botonAgregar.setBackground(new java.awt.Color(66, 139, 202));
        botonAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonAgregar.setForeground(new java.awt.Color(52, 73, 94));
        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar.png"))); // NOI18N
        botonAgregar.setText("Agregar");
        botonAgregar.setContentAreaFilled(false);
        botonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        incrementoVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        incrementoVenta.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 5));
        incrementoVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        incrementoVenta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                incrementoVentaStateChanged(evt);
            }
        });
        incrementoVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                incrementoVentaFocusLost(evt);
            }
        });
        incrementoVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incrementoVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                incrementoVentaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                incrementoVentaMousePressed(evt);
            }
        });
        incrementoVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                incrementoVentaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelProductoLayout = new javax.swing.GroupLayout(panelProducto);
        panelProducto.setLayout(panelProductoLayout);
        panelProductoLayout.setHorizontalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(labelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descripcion))
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addComponent(labelprecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent($)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelcantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDcto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(incrementoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lableImporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(importe, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addComponent(botonAgregar)))
                .addContainerGap())
        );
        panelProductoLayout.setVerticalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescripcion)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelprecio)
                    .addComponent($)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelcantidad)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDcto)
                    .addComponent(incrementoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lableImporte)
                    .addComponent(importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaVendedor.setAutoCreateRowSorter(true);
        tablaVendedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ITEM", "REFERENCIA", "DESCRIPCION", "CANTIDAD", "KILOS", "PRECIO", "DCTO. %", "IMPORTE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVendedor.setGridColor(new java.awt.Color(255, 255, 255));
        tablaVendedor.setShowHorizontalLines(false);
        tablaVendedor.setShowVerticalLines(false);
        tablaVendedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tablaVendedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tablaVendedorFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVendedor);
        if (tablaVendedor.getColumnModel().getColumnCount() > 0) {
            tablaVendedor.getColumnModel().getColumn(1).setResizable(false);
            tablaVendedor.getColumnModel().getColumn(2).setResizable(false);
            tablaVendedor.getColumnModel().getColumn(3).setResizable(false);
            tablaVendedor.getColumnModel().getColumn(4).setResizable(false);
            tablaVendedor.getColumnModel().getColumn(5).setResizable(false);
            tablaVendedor.getColumnModel().getColumn(6).setResizable(false);
            tablaVendedor.getColumnModel().getColumn(7).setResizable(false);
        }

        panelTotal.setBackground(new java.awt.Color(255, 255, 255));
        panelTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));
        panelTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelSub.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSub.setText("Sub-total $:");

        subtotal.setBackground(new java.awt.Color(153, 204, 255));
        subtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subtotal.setForeground(new java.awt.Color(180, 180, 180));
        subtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        subtotal.setText("0");
        subtotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        subtotal.setEnabled(false);
        subtotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                subtotalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                subtotalFocusLost(evt);
            }
        });
        subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalActionPerformed(evt);
            }
        });

        labelPrecioT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPrecioT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPrecioT.setText("IVA $:");

        iva.setBackground(new java.awt.Color(153, 204, 255));
        iva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        iva.setForeground(new java.awt.Color(180, 180, 180));
        iva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        iva.setText("0");
        iva.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        iva.setEnabled(false);
        iva.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ivaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ivaFocusLost(evt);
            }
        });
        iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivaActionPerformed(evt);
            }
        });
        iva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ivaKeyPressed(evt);
            }
        });

        totalT.setBackground(new java.awt.Color(153, 204, 255));
        totalT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalT.setForeground(new java.awt.Color(180, 180, 180));
        totalT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalT.setText("0");
        totalT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        totalT.setEnabled(false);
        totalT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                totalTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                totalTFocusLost(evt);
            }
        });
        totalT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancelar.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setToolTipText("Cancelar registro");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/limpiar.png"))); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.setToolTipText("Limpia formulario");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPreferredSize(new java.awt.Dimension(107, 33));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        botonAgregar1.setBackground(new java.awt.Color(66, 139, 202));
        botonAgregar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonAgregar1.setForeground(new java.awt.Color(52, 73, 94));
        botonAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar.png"))); // NOI18N
        botonAgregar1.setText("Agregar");
        botonAgregar1.setContentAreaFilled(false);
        botonAgregar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelPrecioT1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPrecioT1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPrecioT1.setText("IVA $:");

        abono.setBackground(new java.awt.Color(153, 204, 255));
        abono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        abono.setForeground(new java.awt.Color(204, 204, 255));
        abono.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        abono.setText("0");
        abono.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        abono.setEnabled(false);
        abono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                abonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                abonoFocusLost(evt);
            }
        });

        resto.setBackground(new java.awt.Color(153, 204, 255));
        resto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resto.setForeground(new java.awt.Color(204, 204, 255));
        resto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resto.setText("0");
        resto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        resto.setEnabled(false);
        resto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                restoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restoFocusLost(evt);
            }
        });

        labelResto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelResto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelResto.setText("Resto $:");

        labelAbono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelAbono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAbono.setText("Abono $:");

        javax.swing.GroupLayout panelTotalLayout = new javax.swing.GroupLayout(panelTotal);
        panelTotal.setLayout(panelTotalLayout);
        panelTotalLayout.setHorizontalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalLayout.createSequentialGroup()
                        .addGroup(panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelResto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelAbono, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(abono, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPrecioT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPrecioT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(iva)
                            .addComponent(totalT, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAgregar1)))
                .addContainerGap())
        );
        panelTotalLayout.setVerticalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTotalLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iva, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPrecioT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelResto)))
                    .addGroup(panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelSub, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(abono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelAbono)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPrecioT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalT, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(250, 250, 250));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));

        labelNuevaVenta.setBackground(new java.awt.Color(250, 250, 250));
        labelNuevaVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNuevaVenta.setText("Nueva venta");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ventasInfo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelNuevaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelCapInfVendedorLayout = new javax.swing.GroupLayout(panelCapInfVendedor);
        panelCapInfVendedor.setLayout(panelCapInfVendedorLayout);
        panelCapInfVendedorLayout.setHorizontalGroup(
            panelCapInfVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(panelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelCapInfVendedorLayout.setVerticalGroup(
            panelCapInfVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCapInfVendedorLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCapInfVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCapInfVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void descripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionKeyPressed

    private void descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionActionPerformed

    private void descripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripcionFocusLost
        validation.placeHolder(false,descripcion,"Descripción");
    }//GEN-LAST:event_descripcionFocusLost

    private void descripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripcionFocusGained
        validation.placeHolder(true,descripcion,"Descripción");
    }//GEN-LAST:event_descripcionFocusGained

    private void idProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idProductoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProductoKeyPressed

    private void idProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProductoActionPerformed

    private void idProductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idProductoFocusLost
        validation.placeHolder(false, idProducto, "0");
    }//GEN-LAST:event_idProductoFocusLost

    private void idProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idProductoFocusGained
        validation.placeHolder(true, idProducto, "0");
    }//GEN-LAST:event_idProductoFocusGained

    private void priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceKeyPressed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void priceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceFocusLost
        validation.placeHolder(false,price,"Precio");
    }//GEN-LAST:event_priceFocusLost

    private void priceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceFocusGained
        validation.placeHolder(true,price,"Precio");
    }//GEN-LAST:event_priceFocusGained

    private void cantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidadFocusGained
        validation.placeHolder(true,cantidad,"0");
    }//GEN-LAST:event_cantidadFocusGained

    private void cantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidadFocusLost
       validation.placeHolder(false,cantidad,"0");
    }//GEN-LAST:event_cantidadFocusLost

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void cantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadKeyPressed

    private void importeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_importeFocusGained
         validation.placeHolder(true,importe,"0");
    }//GEN-LAST:event_importeFocusGained

    private void importeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_importeFocusLost
         validation.placeHolder(false,importe,"0");
    }//GEN-LAST:event_importeFocusLost

    private void importeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importeActionPerformed

    private void importeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_importeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_importeKeyPressed

    private void tablaVendedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablaVendedorFocusGained
        
    }//GEN-LAST:event_tablaVendedorFocusGained

    private void tablaVendedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablaVendedorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaVendedorFocusLost

    private void subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotalActionPerformed

    private void subtotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_subtotalFocusGained
         validation.placeHolder(true,subtotal,"0");
    }//GEN-LAST:event_subtotalFocusGained

    private void subtotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_subtotalFocusLost
         validation.placeHolder(false,subtotal,"0");
    }//GEN-LAST:event_subtotalFocusLost

    private void ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ivaActionPerformed

    private void ivaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ivaFocusGained
         validation.placeHolder(true,iva,"0");
    }//GEN-LAST:event_ivaFocusGained

    private void ivaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ivaFocusLost
         validation.placeHolder(false,iva,"0");
    }//GEN-LAST:event_ivaFocusLost

    private void ivaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ivaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ivaKeyPressed

    private void totalTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTActionPerformed

    private void totalTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalTFocusGained
         validation.placeHolder(true,totalT,"0");
    }//GEN-LAST:event_totalTFocusGained

    private void totalTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalTFocusLost
        validation.placeHolder(false,totalT,"0");
    }//GEN-LAST:event_totalTFocusLost

    private void tipoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoVentaActionPerformed

    private void tipoVentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tipoVentaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoVentaFocusGained

    private void tipoVentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tipoVentaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoVentaFocusLost

    private void abonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_abonoFocusGained
        validation.placeHolder(true, abono , "0");
    }//GEN-LAST:event_abonoFocusGained

    private void abonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_abonoFocusLost
        validation.placeHolder(false, abono, "0");
    }//GEN-LAST:event_abonoFocusLost

    private void restoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restoFocusGained
        validation.placeHolder(true, resto, "0");
    }//GEN-LAST:event_restoFocusGained

    private void restoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restoFocusLost
      validation.placeHolder(false, resto, "0");
    }//GEN-LAST:event_restoFocusLost

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, fechaEntrega.getCalendar().get(Calendar.YEAR));
        //Extraer mes
        JOptionPane.showMessageDialog(this, fechaEntrega.getCalendar().get(Calendar.MONTH)+1);
        //Extraer dia
        JOptionPane.showMessageDialog(this, fechaEntrega.getCalendar().get(Calendar.DATE));
        int as = fechaEntrega.getCalendar().get(Calendar.YEAR);
        int asq = fechaEntrega.getCalendar().get(Calendar.MONTH)+1;
        int asqq = fechaEntrega.getCalendar().get(Calendar.DATE);
        System.out.println(as+" "+asq+" "+asqq);
    }//GEN-LAST:event_clienteActionPerformed

    private void clienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clienteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteFocusGained

    private void clienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clienteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteFocusLost

    private void hora2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hora2FocusGained
        // TODO add your handling code here:
        validation.placeHolder(true, hora2,"00");
    }//GEN-LAST:event_hora2FocusGained

    private void hora2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hora2FocusLost
        // TODO add your handling code here:
        validation.placeHolder(false, hora2,"00");
    }//GEN-LAST:event_hora2FocusLost

    private void hora2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hora2ActionPerformed

    private void hora2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hora2KeyPressed
//         TODO add your handling code here:
//        if(evt.getKeyChar()==10)
//        controller.agregaModificaProducto();
    }//GEN-LAST:event_hora2KeyPressed

    private void hora1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hora1FocusGained
        // TODO add your handling code here:
//        validation.placeHolder(true, cantidad01,"0");
//        labelStatus.setText("");
    }//GEN-LAST:event_hora1FocusGained

    private void hora1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hora1FocusLost
        // TODO add your handling code here:
        validation.placeHolder(false, hora1,"0");
    }//GEN-LAST:event_hora1FocusLost

    private void hora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hora1ActionPerformed

    private void hora1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hora1KeyPressed
        // TODO add your handling code here:
//        if(evt.getKeyChar()==10)
//        controller.agregaModificaProducto();
    }//GEN-LAST:event_hora1KeyPressed

    private void hora3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hora3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_hora3FocusGained

    private void hora3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hora3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_hora3FocusLost

    private void hora3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hora3ActionPerformed

    private void lugarEntregaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lugarEntregaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lugarEntregaFocusGained

    private void lugarEntregaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lugarEntregaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lugarEntregaFocusLost

    private void lugarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugarEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugarEntregaActionPerformed

    private void lugarEntregaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lugarEntregaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugarEntregaKeyPressed

    private void incrementoVentaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_incrementoVentaStateChanged
        // TODO add your handling code here:
//        controller.despliegaCuentas();
    }//GEN-LAST:event_incrementoVentaStateChanged

    private void incrementoVentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_incrementoVentaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_incrementoVentaFocusLost

    private void incrementoVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incrementoVentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_incrementoVentaMouseClicked

    private void incrementoVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incrementoVentaMouseEntered

    }//GEN-LAST:event_incrementoVentaMouseEntered

    private void incrementoVentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incrementoVentaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_incrementoVentaMousePressed

    private void incrementoVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_incrementoVentaKeyPressed
        // TODO add your handling code here:
//        if(evt.getKeyChar()==10)
//        controller.agregaModificaProducto();;
    }//GEN-LAST:event_incrementoVentaKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
////        controllerPaneles.addPanel(controllerPaneles.getPanelCentral(), new ViewAdministrarProductos(controllerPaneles, tipoAlmacen)); //asi
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        controller.limpiaCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaFocusGained

    private void fechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaFocusLost

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void fechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel $;
    private javax.swing.JPanel Fecha;
    private javax.swing.JTextField abono;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAgregar1;
    private javax.swing.JButton botonFechaVen1;
    private javax.swing.JTextField cantidad;
    private javax.swing.JComboBox cliente;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField fecha;
    private com.toedter.calendar.JDateChooser fechaEntrega;
    private javax.swing.JTextField hora1;
    private javax.swing.JTextField hora2;
    private javax.swing.JComboBox hora3;
    private javax.swing.JTextField idProducto;
    private javax.swing.JLabel idVenta;
    private javax.swing.JTextField idVentas;
    private javax.swing.JTextField importe;
    private javax.swing.JSpinner incrementoVenta;
    private javax.swing.JTextField iva;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAbono;
    private javax.swing.JLabel labelDcto;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelFecEnt;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelLugEnt;
    private javax.swing.JLabel labelNombreVenta;
    private javax.swing.JLabel labelNuevaVenta;
    private javax.swing.JLabel labelPrecioT;
    private javax.swing.JLabel labelPrecioT1;
    private javax.swing.JLabel labelResto;
    private javax.swing.JLabel labelSub;
    private javax.swing.JLabel labelcantidad;
    private javax.swing.JLabel labelprecio;
    private javax.swing.JLabel lableImporte;
    private javax.swing.JTextField lugarEntrega;
    private javax.swing.JPanel panelCapInfVendedor;
    private javax.swing.JPanel panelProducto;
    private javax.swing.JPanel panelTotal;
    private javax.swing.JTextField price;
    private javax.swing.JTextField resto;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTable tablaVendedor;
    private javax.swing.JComboBox tipoVenta;
    private javax.swing.JTextField totalT;
    // End of variables declaration//GEN-END:variables


}
