/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.ControllerPaneles;
import Controller.ControllerValidation;
import Controller.ControllerViewSession;
import Controller.ControllerViewProveedores;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Carolina
 */
public class ViewAgregarProveedor extends javax.swing.JPanel {
    ControllerValidation validation;
    ControllerPaneles controllerPaneles;
    ControllerViewProveedores controller;

    /**
     * Creates new form ViewAgregarCliente
     */
    public ViewAgregarProveedor(ControllerPaneles controllerPaneles) {
        initComponents();
        this.controllerPaneles = controllerPaneles;//asi
        this.validation = new ControllerValidation();
        this.validationClientes();
    }
    
    public void validationClientes ()
    {
        ArrayList components = new ArrayList<>();
         components.add(pNombre);
        components.add (pApellidoPaterno);
        components.add (pApellidoMaterno);
        components.add (pRFC);
        components.add (pMarca);
        components.add (pEmpresa);  
        components.add (pTelefono);
        components.add (pTelCelular);
        components.add (pEmail);
        components.add (pCalle);
        components.add (pCiudad);
        components.add (pColonia);
        components.add (pEstados);
        components.add (pCP);
        components.add (pNoExt);
        components.add (pNoInt);
        
        controller = new ControllerViewProveedores(components);
        controller.validations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pApellidoPaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pApellidoMaterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pRFC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pTelCelular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pEmail = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pCalle = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pNoExt = new javax.swing.JTextField();
        pNoInt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pColonia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pCiudad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pCP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pEstados = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        acIdCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        pMarca = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        pEmpresa = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 246, 247));
        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre: ");

        pNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pNombre.setForeground(new java.awt.Color(180, 180, 180));
        pNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pNombre.setText("Nombre");
        pNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pNombreFocusLost(evt);
            }
        });
        pNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNombreActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Apellido Paterno:");

        pApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pApellidoPaterno.setForeground(new java.awt.Color(180, 180, 180));
        pApellidoPaterno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pApellidoPaterno.setText("Apellido Paterno");
        pApellidoPaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pApellidoPaternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pApellidoPaternoFocusLost(evt);
            }
        });
        pApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pApellidoPaternoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Apellido Materno:");

        pApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pApellidoMaterno.setForeground(new java.awt.Color(180, 180, 180));
        pApellidoMaterno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pApellidoMaterno.setText("Apellido Materno");
        pApellidoMaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pApellidoMaternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pApellidoMaternoFocusLost(evt);
            }
        });
        pApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pApellidoMaternoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("RFC:");

        pRFC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pRFC.setForeground(new java.awt.Color(180, 180, 180));
        pRFC.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pRFC.setText("RFC");
        pRFC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pRFCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pRFCFocusLost(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Email:");

        pTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pTelefono.setForeground(new java.awt.Color(180, 180, 180));
        pTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pTelefono.setText("xx-xxx-xxxxxxx");
        pTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pTelefonoFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Teléfono:");

        pTelCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pTelCelular.setForeground(new java.awt.Color(180, 180, 180));
        pTelCelular.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pTelCelular.setText("xx-xxx-xxxxxxx");
        pTelCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pTelCelularFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pTelCelularFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tel. Celular:");

        pEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pEmail.setForeground(new java.awt.Color(180, 180, 180));
        pEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pEmail.setText("cliente@reposteria.com");
        pEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pEmailFocusLost(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Calle:");

        pCalle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pCalle.setForeground(new java.awt.Color(180, 180, 180));
        pCalle.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pCalle.setText("Calle");
        pCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pCalleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pCalleFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("No. Ext:");

        pNoExt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pNoExt.setForeground(new java.awt.Color(180, 180, 180));
        pNoExt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pNoExt.setText("No. Ext.");
        pNoExt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pNoExtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pNoExtFocusLost(evt);
            }
        });

        pNoInt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pNoInt.setForeground(new java.awt.Color(180, 180, 180));
        pNoInt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pNoInt.setText("No. Int");
        pNoInt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pNoIntFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pNoIntFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Colonia:");

        pColonia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pColonia.setForeground(new java.awt.Color(180, 180, 180));
        pColonia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pColonia.setText("Colonia");
        pColonia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pColoniaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pColoniaFocusLost(evt);
            }
        });
        pColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pColoniaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Ciudad:");

        pCiudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pCiudad.setForeground(new java.awt.Color(180, 180, 180));
        pCiudad.setText("Ciudad");
        pCiudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pCiudadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pCiudadFocusLost(evt);
            }
        });
        pCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pCiudadActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("C.P:");

        pCP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pCP.setForeground(new java.awt.Color(180, 180, 180));
        pCP.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pCP.setText("xxxxx");
        pCP.setToolTipText("");
        pCP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pCPFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Estado:");

        pEstados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pEstados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Coahuila", "Colima", "Distrito Federal", "Durango", "Estado de México", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas" }));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("No. Int");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(66, 139, 202));
        jLabel18.setText("Dirección");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(pCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(109, 109, 109))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addComponent(pNoExt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pNoInt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pCP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pNoExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(pNoInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(pEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)))
        );

        acIdCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acIdCliente.setForeground(new java.awt.Color(180, 180, 180));
        acIdCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        acIdCliente.setText("Id Proveedor");
        acIdCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acIdClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                acIdClienteFocusLost(evt);
            }
        });
        acIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acIdClienteActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setPreferredSize(new java.awt.Dimension(107, 33));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tick-outline.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/times-outline.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Marca:");
        jLabel19.setToolTipText("");

        pMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pMarca.setForeground(new java.awt.Color(180, 180, 180));
        pMarca.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pMarca.setText("Marca");
        pMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pMarcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pMarcaFocusLost(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Empresa:");

        pEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pEmpresa.setForeground(new java.awt.Color(180, 180, 180));
        pEmpresa.setText("Empresa");
        pEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pEmpresaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pEmpresaFocusLost(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(66, 139, 202));
        jLabel22.setText("Información personal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(acIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pEmpresa))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(26, 26, 26))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(pApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(pApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel19)
                    .addComponent(pMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(pEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(250, 250, 250));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));

        jLabel25.setBackground(new java.awt.Color(250, 250, 250));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/proveedoresInfo.png"))); // NOI18N
        jLabel25.setText("Agregar nuevo cliente");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acIdClienteActionPerformed

    private void acIdClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acIdClienteFocusGained
        validation.placeHolder(true,acIdCliente,"Id Cliente"); // TODO add your handling code here:
    }//GEN-LAST:event_acIdClienteFocusGained

    private void pNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNombreActionPerformed

    private void acIdClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acIdClienteFocusLost
        validation.placeHolder(false,acIdCliente,"Id Cliente");// TODO add your handling code here:
    }//GEN-LAST:event_acIdClienteFocusLost

    private void pNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pNombreFocusGained
        validation.placeHolder(true,pNombre,"Nombre");        // TODO add your handling code here:
    }//GEN-LAST:event_pNombreFocusGained

    private void pNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pNombreFocusLost
        validation.placeHolder(false,pNombre,"Nombre");         // TODO add your handling code here:
    }//GEN-LAST:event_pNombreFocusLost

    private void pApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pApellidoPaternoActionPerformed

    private void pApellidoPaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pApellidoPaternoFocusGained
        validation.placeHolder(true,pApellidoPaterno,"Apellido Paterno");        // TODO add your handling code here:
    }//GEN-LAST:event_pApellidoPaternoFocusGained

    private void pApellidoPaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pApellidoPaternoFocusLost
       validation.placeHolder(false, pApellidoPaterno,"Apellido Paterno"); // TODO add your handling code here:
    }//GEN-LAST:event_pApellidoPaternoFocusLost

    private void pApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pApellidoMaternoActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_pApellidoMaternoActionPerformed

    private void pApellidoMaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pApellidoMaternoFocusGained
        validation.placeHolder(true,pApellidoMaterno,"Apellido Materno");        // TODO add your handling code here:
    }//GEN-LAST:event_pApellidoMaternoFocusGained

    private void pApellidoMaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pApellidoMaternoFocusLost
        validation.placeHolder(false,pApellidoMaterno,"Apellido Materno");        // TODO add your handling code here:
    }//GEN-LAST:event_pApellidoMaternoFocusLost

    private void pRFCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pRFCFocusGained
        validation.placeHolder(true,pRFC,"RFC");        // TODO add your handling code here:
    }//GEN-LAST:event_pRFCFocusGained

    private void pRFCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pRFCFocusLost
        validation.placeHolder(false,pRFC,"RFC");        // TODO add your handling code here:
    }//GEN-LAST:event_pRFCFocusLost

    private void pTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pTelefonoFocusGained
        validation.placeHolder(true,pTelefono,"xx-xxx-xxxxxxx");        // TODO add your handling code here:
    }//GEN-LAST:event_pTelefonoFocusGained

    private void pTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pTelefonoFocusLost
        validation.placeHolder(false,pTelefono,"xx-xxx-xxxxxxx");        // TODO add your handling code here:
    }//GEN-LAST:event_pTelefonoFocusLost

    private void pTelCelularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pTelCelularFocusGained
        validation.placeHolder(true,pTelCelular,"xx-xxx-xxxxxxx");        // TODO add your handling code here:
    }//GEN-LAST:event_pTelCelularFocusGained

    private void pTelCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pTelCelularFocusLost
        validation.placeHolder(false,pTelCelular,"xx-xxx-xxxxxxx");        // TODO add your handling code here:
    }//GEN-LAST:event_pTelCelularFocusLost

    private void pEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pEmailFocusGained
        validation.placeHolder(true,pEmail,"cliente@reposteria.com");        // TODO add your handling code here:
    }//GEN-LAST:event_pEmailFocusGained

    private void pEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pEmailFocusLost
        validation.placeHolder(false,pEmail,"cliente@reposteria.com");        // TODO add your handling code here:
    }//GEN-LAST:event_pEmailFocusLost

    private void pCalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pCalleFocusGained
        validation.placeHolder(true,pCalle,"Calle");        // TODO add your handling code here:
    }//GEN-LAST:event_pCalleFocusGained

    private void pCalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pCalleFocusLost
        validation.placeHolder(false,pCalle,"Calle");        // TODO add your handling code here:
    }//GEN-LAST:event_pCalleFocusLost

    private void pNoExtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pNoExtFocusGained
        validation.placeHolder(true,pNoExt,"No. Ext");        // TODO add your handling code here:
    }//GEN-LAST:event_pNoExtFocusGained

    private void pNoExtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pNoExtFocusLost
        validation.placeHolder(false,pNoExt,"No. Ext");        // TODO add your handling code here:
    }//GEN-LAST:event_pNoExtFocusLost

    private void pNoIntFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pNoIntFocusGained
        validation.placeHolder(true,pNoInt,"No. Int");       // TODO add your handling code here:
    }//GEN-LAST:event_pNoIntFocusGained

    private void pNoIntFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pNoIntFocusLost
        validation.placeHolder(false,pNoInt,"No. Int");        // TODO add your handling code here:
    }//GEN-LAST:event_pNoIntFocusLost

    private void pColoniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pColoniaFocusGained
        validation.placeHolder(true,pColonia,"Colonia");        // TODO add your handling code here:
    }//GEN-LAST:event_pColoniaFocusGained

    private void pColoniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pColoniaFocusLost
        validation.placeHolder(false,pColonia,"Colonia");        // TODO add your handling code here:
    }//GEN-LAST:event_pColoniaFocusLost

    private void pCiudadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pCiudadFocusGained
        validation.placeHolder(true,pCiudad,"Ciudad");        // TODO add your handling code here:
    }//GEN-LAST:event_pCiudadFocusGained

    private void pCiudadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pCiudadFocusLost
        validation.placeHolder(false,pCiudad,"Ciudad");        // TODO add your handling code here:
    }//GEN-LAST:event_pCiudadFocusLost

    private void pCPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pCPFocusGained
        validation.placeHolder(true,pCP,"xxxxx");        // TODO add your handling code here:
    }//GEN-LAST:event_pCPFocusGained

    private void pCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pCiudadActionPerformed

    private void pColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pColoniaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       controllerPaneles.addPanel(controllerPaneles.getPanelCentral(), new ViewProveedor(controllerPaneles)); //asi
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pMarcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pMarcaFocusGained
        validation.placeHolder(true,pMarca,"Marca");       // TODO add your handling code here:
    }//GEN-LAST:event_pMarcaFocusGained

    private void pMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pMarcaFocusLost
        validation.placeHolder(false,pMarca,"Marca");         // TODO add your handling code here:
    }//GEN-LAST:event_pMarcaFocusLost

    private void pEmpresaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pEmpresaFocusGained
        validation.placeHolder(true,pEmpresa,"Empresa");         // TODO add your handling code here:
    }//GEN-LAST:event_pEmpresaFocusGained

    private void pEmpresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pEmpresaFocusLost
        validation.placeHolder(false,pEmpresa,"Empresa");        // TODO add your handling code here:
    }//GEN-LAST:event_pEmpresaFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acIdCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField pApellidoMaterno;
    private javax.swing.JTextField pApellidoPaterno;
    private javax.swing.JTextField pCP;
    private javax.swing.JTextField pCalle;
    private javax.swing.JTextField pCiudad;
    private javax.swing.JTextField pColonia;
    private javax.swing.JTextField pEmail;
    private javax.swing.JTextField pEmpresa;
    private javax.swing.JComboBox pEstados;
    private javax.swing.JTextField pMarca;
    private javax.swing.JTextField pNoExt;
    private javax.swing.JTextField pNoInt;
    private javax.swing.JTextField pNombre;
    private javax.swing.JTextField pRFC;
    private javax.swing.JTextField pTelCelular;
    private javax.swing.JTextField pTelefono;
    // End of variables declaration//GEN-END:variables
}
