/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.ControllerClockPanel;
import Controller.ControllerDatePanel;
import Controller.ControllerViewAdministrador;
import Model.ModelEmpresa;
import Model.ModelUsuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author Jesus
 */
public class ViewBasePrincipal extends javax.swing.JFrame {
    ModelEmpresa modelEmpresa;
    ModelUsuario modelUsuario;
    ControllerClockPanel hiloHora;
    public static int idUsuario;
    ControllerViewAdministrador controller;
    /**
     * Creates new form principal
     * @param modelEmpresa
     * @param modelUsuario
     */
    public ViewBasePrincipal(ModelEmpresa modelEmpresa, ModelUsuario modelUsuario) {
        this.modelEmpresa = modelEmpresa;
        this.modelUsuario = modelUsuario;
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/iconEmpresa.png"));
        setIconImage(icon);
        initClock();
        initFecha();
        configIniciales();
        addPanel(panelBotoneraPrincipal, new ViewBaseAdministradorBotoneraPrincipal());
        addPanel(paneCentral, new ViewBaseAdministrador());
        labelBienvenida.setText("Bienvenido Jesús Salazar");
    }
    
    private void initFecha(){
       jLabelFecha.setText(ControllerDatePanel.getFecha());
    }
    
    private void initClock(){
        hiloHora = new ControllerClockPanel(jLabelHora);
        Thread clock=new Thread(hiloHora);
        clock.start();
    }
    
    private void configIniciales(){
        Dimension dim = super.getToolkit().getScreenSize(); 
        super.setBackground(new Color(44,62,80));
        super.setSize(dim); 
        super.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        panelBotoneraPrincipal.setLayout(new GridBagLayout());
        panelBotoneraPrincipal.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        panelBotoneraPrincipal.setVisible(true);
        paneCentral.setLayout(new GridBagLayout());
        paneCentral.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        paneCentral.setVisible(true);
    }
    
    private void addPanel(JPanel base, JPanel panel){
        base.removeAll();
        base.add(panel);
        base.updateUI();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        BCerrar = new javax.swing.JButton();
        BMin = new javax.swing.JButton();
        jLabelFecha = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        panelBotoneraPrincipal = new javax.swing.JPanel();
        paneCentral = new javax.swing.JPanel();
        panelBotoneraPrincipal1 = new javax.swing.JPanel();
        labelBienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanelBase.setBackground(new java.awt.Color(255, 255, 255));

        panelTitulo.setBackground(new java.awt.Color(245, 246, 247));
        panelTitulo.setForeground(new java.awt.Color(0, 51, 51));

        BCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IconClose.png"))); // NOI18N
        BCerrar.setToolTipText("Salir");
        BCerrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BCerrar.setBorderPainted(false);
        BCerrar.setContentAreaFilled(false);
        BCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCerrarActionPerformed(evt);
            }
        });

        BMin.setBackground(new java.awt.Color(255, 255, 255));
        BMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/minim.png"))); // NOI18N
        BMin.setToolTipText("Minimizar");
        BMin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BMin.setBorderPainted(false);
        BMin.setContentAreaFilled(false);
        BMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMinActionPerformed(evt);
            }
        });

        jLabelFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(51, 51, 51));
        jLabelFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFecha.setText("Fecha");

        jLabelHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(51, 51, 51));
        jLabelHora.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHora.setText("Clock");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BCerrar)
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(BMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelBotoneraPrincipal.setBackground(new java.awt.Color(43, 53, 66));

        javax.swing.GroupLayout panelBotoneraPrincipalLayout = new javax.swing.GroupLayout(panelBotoneraPrincipal);
        panelBotoneraPrincipal.setLayout(panelBotoneraPrincipalLayout);
        panelBotoneraPrincipalLayout.setHorizontalGroup(
            panelBotoneraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelBotoneraPrincipalLayout.setVerticalGroup(
            panelBotoneraPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        paneCentral.setBackground(new java.awt.Color(245, 246, 247));
        paneCentral.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout paneCentralLayout = new javax.swing.GroupLayout(paneCentral);
        paneCentral.setLayout(paneCentralLayout);
        paneCentralLayout.setHorizontalGroup(
            paneCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        paneCentralLayout.setVerticalGroup(
            paneCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        panelBotoneraPrincipal1.setBackground(new java.awt.Color(53, 66, 81));

        labelBienvenida.setBackground(new java.awt.Color(245, 246, 247));
        labelBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelBienvenida.setForeground(new java.awt.Color(245, 246, 247));
        labelBienvenida.setText("Bienvenido");

        javax.swing.GroupLayout panelBotoneraPrincipal1Layout = new javax.swing.GroupLayout(panelBotoneraPrincipal1);
        panelBotoneraPrincipal1.setLayout(panelBotoneraPrincipal1Layout);
        panelBotoneraPrincipal1Layout.setHorizontalGroup(
            panelBotoneraPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoneraPrincipal1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(labelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotoneraPrincipal1Layout.setVerticalGroup(
            panelBotoneraPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoneraPrincipal1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paneCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBotoneraPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBotoneraPrincipal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelBotoneraPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelBotoneraPrincipal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(paneCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BCerrarActionPerformed

    private void BMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMinActionPerformed
        // TODO add your handling code here:
        setExtendedState(ViewBasePrincipal.CROSSHAIR_CURSOR); 
    }//GEN-LAST:event_BMinActionPerformed

    public void agregaJPanel(JPanel panelBase, JPanel panelAdd)
    {
        panelBase.removeAll();
        panelBase.add(panelAdd,LEFT_ALIGNMENT);
        panelBase.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCerrar;
    private javax.swing.JButton BMin;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JLabel labelBienvenida;
    private javax.swing.JPanel paneCentral;
    private javax.swing.JPanel panelBotoneraPrincipal;
    private javax.swing.JPanel panelBotoneraPrincipal1;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
