/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerPaneles;
import Controller.ControllerValidation;
import Controller.ControllerViewProducto;
import Model.ModelCategoria;
import Model.ModelEmpresa;
import Model.ModelProducto;
import Model.ModelProveedor;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Jesus
 */
public class ViewGeneraVenta extends javax.swing.JPanel {
    ControllerPaneles controllerPaneles;
    ControllerValidation validation;
    ControllerViewProducto controller;
    ModelEmpresa modelEmpresa;
    ModelProducto prodcutoTemp;
    List<ModelProveedor> listProveedores;
    List<ModelCategoria> listCategoria;
    boolean tipoAlmacen;
    /**
     * Creates new form ViewBaseAdministrador
     * @param controllerPaneles
     * @param user
     * @param tipoProducto
     */
    public ViewGeneraVenta(ControllerPaneles controllerPaneles, ModelProducto user,boolean tipoAlmacen) {
        this.tipoAlmacen=tipoAlmacen;
        this.prodcutoTemp = user;
        this.validation = new ControllerValidation();
        this.controllerPaneles = controllerPaneles;
        this.modelEmpresa = controllerPaneles.getModelEmpresa();
        initComponents();
        validation();
        labelStatus02.setText("");
        eliminar.setVisible(false);
        for (int i = 0; i < 4; i++)
            controller.cargarCombo(i,tipoAlmacen);
        if(user==null){
            if(tipoAlmacen)
                labelRuta.setText("Administración de almacén / Nuevo producto almacén");
            else
                labelRuta.setText("Administración de productos / Nuevo producto tienda");

        }else{
            if(tipoAlmacen)
                labelRuta.setText("Administración de almacén / Modifica producto almacén");
            else
                labelRuta.setText("Administración de productos / Modifica producto");
        }
        labelStatus.setText("");
    }
    
    private void validation(){
        ArrayList components = new ArrayList<>();
        components.add(idProducto);
        components.add(idCategoria);
        components.add(idProveedor);
        components.add(ID);
        components.add(nombre);
        components.add(cantidad01);
        components.add(cantidad02);
        components.add(tipoUnidad);
        components.add(unidadExistencia);
        components.add(minStock);
        components.add(maxStock);
        components.add(precioCompra01);
        components.add(precioCompra02);
        components.add(incrementoVenta);
        components.add(precioVenta01);
        components.add(imagen);
        components.add(gananciaIndividual);
        components.add(gananciaTotal);
        components.add(inversion);
        components.add(labelStatus);
        components.add(labelStatus02);
        components.add(eliminar);
        components.add(tipoAlmacen);
        controller = new ControllerViewProducto(components);
        controller.validations();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        labelRuta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cantidad01 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        tipoUnidad = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        unidadExistencia = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        incrementoVenta = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        minStock = new javax.swing.JSpinner();
        maxStock = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        panelImagen = new javax.swing.JPanel();
        imagen = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        idCategoria = new javax.swing.JComboBox();
        labelNota = new javax.swing.JLabel();
        cantidad02 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        precioCompra01 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        precioCompra02 = new javax.swing.JTextField();
        precioVenta01 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        gananciaIndividual = new javax.swing.JTextField();
        gananciaTotal = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        inversion = new javax.swing.JTextField();
        idProveedor = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        idProducto = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        labelStatus02 = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 246, 247));
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel4.setBackground(new java.awt.Color(250, 250, 250));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));

        labelRuta.setBackground(new java.awt.Color(250, 250, 250));
        labelRuta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelRuta.setForeground(new java.awt.Color(53, 107, 161));
        labelRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ajustesProducto.png"))); // NOI18N
        labelRuta.setText("Administración de almacen / Nuevo producto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(labelRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRuta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 1, true));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(53, 107, 161));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/regresar.png"))); // NOI18N
        jButton4.setText("Administración de productos");
        jButton4.setToolTipText("Regresar");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setPreferredSize(new java.awt.Dimension(107, 33));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/limpiar.png"))); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.setToolTipText("Limpia formulario");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPreferredSize(new java.awt.Dimension(107, 33));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancelar.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setToolTipText("Cancelar registro");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.setToolTipText("Ingresa registro");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(66, 139, 202));
        jLabel20.setText("Nuevo producto para almacén:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Nombre:");

        nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(180, 180, 180));
        nombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nombre.setText("Nombre del producto");
        nombre.setPreferredSize(new java.awt.Dimension(49, 28));
        nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreFocusLost(evt);
            }
        });
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreKeyPressed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Peso:");

        cantidad01.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cantidad01.setForeground(new java.awt.Color(180, 180, 180));
        cantidad01.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cantidad01.setText("0");
        cantidad01.setPreferredSize(new java.awt.Dimension(49, 28));
        cantidad01.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad01FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad01FocusLost(evt);
            }
        });
        cantidad01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad01ActionPerformed(evt);
            }
        });
        cantidad01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidad01KeyPressed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/categoria.png"))); // NOI18N
        jButton5.setText("Nueva categoría");
        jButton5.setToolTipText("Agrega nueva categoría");
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setPreferredSize(new java.awt.Dimension(107, 33));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tipoUnidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoUnidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kg", "g", "L", "mL" }));
        tipoUnidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tipoUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoUnidadActionPerformed(evt);
            }
        });
        tipoUnidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tipoUnidadKeyPressed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Unidades: #");

        unidadExistencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        unidadExistencia.setForeground(new java.awt.Color(180, 180, 180));
        unidadExistencia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        unidadExistencia.setText("0");
        unidadExistencia.setPreferredSize(new java.awt.Dimension(49, 28));
        unidadExistencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                unidadExistenciaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                unidadExistenciaFocusLost(evt);
            }
        });
        unidadExistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadExistenciaActionPerformed(evt);
            }
        });
        unidadExistencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                unidadExistenciaKeyPressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Minimo Stock:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Maximo Stock:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Precio compra: $");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Incremento venta: %");

        incrementoVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        incrementoVenta.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 5));
        incrementoVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        incrementoVenta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                incrementoVentaStateChanged(evt);
            }
        });
        incrementoVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                incrementoVentaFocusLost(evt);
            }
        });
        incrementoVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incrementoVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                incrementoVentaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                incrementoVentaMousePressed(evt);
            }
        });
        incrementoVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                incrementoVentaKeyPressed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Precio venta: $");

        minStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        minStock.setModel(new javax.swing.SpinnerNumberModel(5, 0, 9999, 1));
        minStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                minStockKeyPressed(evt);
            }
        });

        maxStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maxStock.setModel(new javax.swing.SpinnerNumberModel(10, 0, 9999, 1));
        maxStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maxStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                maxStockKeyPressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Código: #");

        ID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(180, 180, 180));
        ID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ID.setText("Código de barras");
        ID.setPreferredSize(new java.awt.Dimension(49, 28));
        ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDFocusLost(evt);
            }
        });
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IDKeyPressed(evt);
            }
        });

        panelImagen.setBackground(new java.awt.Color(255, 255, 255));
        panelImagen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));

        imagen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buscaImagen.png"))); // NOI18N
        imagen.setToolTipText("Cargar foto de producto");
        imagen.setContentAreaFilled(false);
        imagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imagen.setPreferredSize(new java.awt.Dimension(107, 33));
        imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Categoría:");

        idCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona categoría" }));
        idCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCategoriaActionPerformed(evt);
            }
        });
        idCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idCategoriaKeyPressed(evt);
            }
        });

        labelNota.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelNota.setForeground(new java.awt.Color(66, 139, 202));
        labelNota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNota.setText("Nota: Todos los campos son obligatorios.");

        cantidad02.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cantidad02.setForeground(new java.awt.Color(180, 180, 180));
        cantidad02.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cantidad02.setText("00");
        cantidad02.setPreferredSize(new java.awt.Dimension(49, 28));
        cantidad02.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidad02FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidad02FocusLost(evt);
            }
        });
        cantidad02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad02ActionPerformed(evt);
            }
        });
        cantidad02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidad02KeyPressed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(66, 139, 202));
        jLabel31.setText(".");

        precioCompra01.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        precioCompra01.setForeground(new java.awt.Color(180, 180, 180));
        precioCompra01.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precioCompra01.setText("0");
        precioCompra01.setPreferredSize(new java.awt.Dimension(49, 28));
        precioCompra01.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                precioCompra01FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                precioCompra01FocusLost(evt);
            }
        });
        precioCompra01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioCompra01ActionPerformed(evt);
            }
        });
        precioCompra01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                precioCompra01KeyPressed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(66, 139, 202));
        jLabel32.setText(".");

        precioCompra02.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        precioCompra02.setForeground(new java.awt.Color(180, 180, 180));
        precioCompra02.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        precioCompra02.setText("00");
        precioCompra02.setPreferredSize(new java.awt.Dimension(49, 28));
        precioCompra02.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                precioCompra02FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                precioCompra02FocusLost(evt);
            }
        });
        precioCompra02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioCompra02ActionPerformed(evt);
            }
        });
        precioCompra02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                precioCompra02KeyPressed(evt);
            }
        });

        precioVenta01.setEditable(false);
        precioVenta01.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        precioVenta01.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precioVenta01.setText("0");
        precioVenta01.setPreferredSize(new java.awt.Dimension(49, 28));
        precioVenta01.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                precioVenta01FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                precioVenta01FocusLost(evt);
            }
        });
        precioVenta01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioVenta01ActionPerformed(evt);
            }
        });
        precioVenta01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                precioVenta01KeyPressed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("Ganancía c/u: $");

        gananciaIndividual.setEditable(false);
        gananciaIndividual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gananciaIndividual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        gananciaIndividual.setText("0");
        gananciaIndividual.setPreferredSize(new java.awt.Dimension(49, 28));
        gananciaIndividual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gananciaIndividualFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gananciaIndividualFocusLost(evt);
            }
        });
        gananciaIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gananciaIndividualActionPerformed(evt);
            }
        });
        gananciaIndividual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gananciaIndividualKeyPressed(evt);
            }
        });

        gananciaTotal.setEditable(false);
        gananciaTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gananciaTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        gananciaTotal.setText("0");
        gananciaTotal.setPreferredSize(new java.awt.Dimension(49, 28));
        gananciaTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gananciaTotalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gananciaTotalFocusLost(evt);
            }
        });
        gananciaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gananciaTotalActionPerformed(evt);
            }
        });
        gananciaTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gananciaTotalKeyPressed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("Ganancía total: $");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("Inversion: $");

        inversion.setEditable(false);
        inversion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inversion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inversion.setText("0");
        inversion.setPreferredSize(new java.awt.Dimension(49, 28));
        inversion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inversionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inversionFocusLost(evt);
            }
        });
        inversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inversionActionPerformed(evt);
            }
        });
        inversion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inversionKeyPressed(evt);
            }
        });

        idProveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona proveedor" }));
        idProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProveedorActionPerformed(evt);
            }
        });
        idProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idProveedorKeyPressed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("Producto:");

        idProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nuevo producto" }));
        idProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProductoActionPerformed(evt);
            }
        });
        idProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idProductoKeyPressed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Proveedor:");

        labelStatus02.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelStatus02.setForeground(new java.awt.Color(66, 139, 202));
        labelStatus02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStatus02.setText("categoría almacenada con éxito");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNota, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(precioCompra01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(precioCompra02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(incrementoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(inversion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(precioVenta01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(gananciaIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(gananciaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(unidadExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(cantidad01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel31)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cantidad02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(minStock, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(maxStock, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(idProveedor, javax.swing.GroupLayout.Alignment.LEADING, 0, 400, Short.MAX_VALUE)
                                        .addComponent(labelStatus02, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(idProducto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(idCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(labelNota))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelStatus02, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad01, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(cantidad02, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidadExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioCompra01, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(precioCompra02, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incrementoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gananciaIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gananciaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inversion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioVenta01, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        labelStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(66, 139, 202));
        labelStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStatus.setText("categoría almacenada con éxito");

        eliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eliminar.png"))); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.setToolTipText("Limpia formulario");
        eliminar.setContentAreaFilled(false);
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.setPreferredSize(new java.awt.Dimension(107, 33));
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controllerPaneles.addPanel(controllerPaneles.getPanelCentral(), new ViewAdministrarProductos(controllerPaneles, tipoAlmacen)); //asi
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        controller.agregaModificaProducto();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        controller.limpiaCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            controllerPaneles.addPanel(controllerPaneles.getPanelCentral(), new ViewAdministrarProductos(controllerPaneles, tipoAlmacen)); //asi
    }//GEN-LAST:event_jButton4ActionPerformed

    private void nombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFocusGained
        // TODO add your handling code here:
        validation.placeHolder(true, nombre,"Nombre del producto");
        labelStatus.setText("");
    }//GEN-LAST:event_nombreFocusGained

    private void nombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFocusLost
        // TODO add your handling code here:
        validation.placeHolder(false, nombre,"Nombre del producto");
    }//GEN-LAST:event_nombreFocusLost

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10)
            controller.agregaModificaProducto();
    }//GEN-LAST:event_nombreKeyPressed

    private void cantidad01FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad01FocusGained
        // TODO add your handling code here:
        validation.placeHolder(true, cantidad01,"0");
        labelStatus.setText("");
    }//GEN-LAST:event_cantidad01FocusGained

    private void cantidad01FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad01FocusLost
        // TODO add your handling code here:
        validation.placeHolder(false, cantidad01,"0");
    }//GEN-LAST:event_cantidad01FocusLost

    private void cantidad01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad01ActionPerformed

    private void cantidad01KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad01KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10)
            controller.agregaModificaProducto();   
    }//GEN-LAST:event_cantidad01KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        controllerPaneles.addPanel(controllerPaneles.getPanelCentral(), new ViewCategoria(controllerPaneles, null,tipoAlmacen)); //asi
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tipoUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoUnidadActionPerformed

    private void tipoUnidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipoUnidadKeyPressed
        if(evt.getKeyChar()==10)
            controller.agregaModificaProducto();         // TODO add your handling code here:
    }//GEN-LAST:event_tipoUnidadKeyPressed

    private void unidadExistenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unidadExistenciaFocusGained
        // TODO add your handling code here:
        validation.placeHolder(true, unidadExistencia,"0");
        labelStatus.setText("");
    }//GEN-LAST:event_unidadExistenciaFocusGained

    private void unidadExistenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unidadExistenciaFocusLost
        // TODO add your handling code here:
        validation.placeHolder(false, unidadExistencia,"0");
        controller.despliegaCuentas();
    }//GEN-LAST:event_unidadExistenciaFocusLost

    private void unidadExistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadExistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadExistenciaActionPerformed

    private void unidadExistenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unidadExistenciaKeyPressed
        if(evt.getKeyChar()==10)
            controller.agregaModificaProducto(); 
    }//GEN-LAST:event_unidadExistenciaKeyPressed

    private void IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFocusGained
        // TODO add your handling code here:
        validation.placeHolder(true,ID,"Código de barras");
        labelStatus.setText("");
    }//GEN-LAST:event_IDFocusGained

    private void IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFocusLost
        // TODO add your handling code here:
        validation.placeHolder(false,ID,"Código de barras");
    }//GEN-LAST:event_IDFocusLost

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10)
            controller.agregaModificaProducto();
    }//GEN-LAST:event_IDKeyPressed

    private void idCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCategoriaActionPerformed

    private void idCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idCategoriaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10)
            controller.agregaModificaProducto();
    }//GEN-LAST:event_idCategoriaKeyPressed

    private void minStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minStockKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10)
            controller.agregaModificaProducto();
    }//GEN-LAST:event_minStockKeyPressed

    private void maxStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maxStockKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10)
            controller.agregaModificaProducto();
    }//GEN-LAST:event_maxStockKeyPressed

    private void incrementoVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_incrementoVentaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10)
            controller.agregaModificaProducto();;
    }//GEN-LAST:event_incrementoVentaKeyPressed

    private void cantidad02FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad02FocusGained
        // TODO add your handling code here:
        validation.placeHolder(true, cantidad02,"00");
        labelStatus.setText("");
    }//GEN-LAST:event_cantidad02FocusGained

    private void cantidad02FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidad02FocusLost
        // TODO add your handling code here:
        validation.placeHolder(false, cantidad02,"00");
        controller.despliegaCuentas();
    }//GEN-LAST:event_cantidad02FocusLost

    private void cantidad02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad02ActionPerformed

    private void cantidad02KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad02KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10)
            controller.agregaModificaProducto();
    }//GEN-LAST:event_cantidad02KeyPressed

    private void precioCompra01FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioCompra01FocusGained
        // TODO add your handling code here:
        validation.placeHolder(true, precioCompra01,"0");
        labelStatus.setText("");
    }//GEN-LAST:event_precioCompra01FocusGained

    private void precioCompra01FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioCompra01FocusLost
        // TODO add your handling code here:
        validation.placeHolder(false, precioCompra01,"0");
        controller.despliegaCuentas();
    }//GEN-LAST:event_precioCompra01FocusLost

    private void precioCompra01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioCompra01ActionPerformed
        // TODO add your handling code here:
//        precioVenta.setText(""+controller.calcularPrecioReal());
    }//GEN-LAST:event_precioCompra01ActionPerformed

    private void precioCompra01KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioCompra01KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10)
            controller.agregaModificaProducto();
    }//GEN-LAST:event_precioCompra01KeyPressed

    private void precioCompra02FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioCompra02FocusGained
        // TODO add your handling code here:
        validation.placeHolder(true, precioCompra02,"00");
        labelStatus.setText("");
    }//GEN-LAST:event_precioCompra02FocusGained

    private void precioCompra02FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioCompra02FocusLost
        // TODO add your handling code here:
        validation.placeHolder(false, precioCompra02,"00");
        controller.despliegaCuentas();
    }//GEN-LAST:event_precioCompra02FocusLost

    private void precioCompra02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioCompra02ActionPerformed
        // TODO add your handling code here:
//        precioVenta.setText(""+controller.calcularPrecioReal());
    }//GEN-LAST:event_precioCompra02ActionPerformed

    private void precioCompra02KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioCompra02KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10)
            controller.agregaModificaProducto();        
    }//GEN-LAST:event_precioCompra02KeyPressed

    private void precioVenta01FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioVenta01FocusGained
        // TODO add your handling code here:
        validation.placeHolder(true, precioCompra02,"0");
        labelStatus.setText("");
    }//GEN-LAST:event_precioVenta01FocusGained

    private void precioVenta01FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioVenta01FocusLost
        // TODO add your handling code here:
        validation.placeHolder(false, precioCompra02,"0");
    }//GEN-LAST:event_precioVenta01FocusLost

    private void precioVenta01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioVenta01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioVenta01ActionPerformed

    private void precioVenta01KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioVenta01KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10)
            controller.agregaModificaProducto();          
    }//GEN-LAST:event_precioVenta01KeyPressed

    private void incrementoVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incrementoVentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_incrementoVentaMouseClicked

    private void incrementoVentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_incrementoVentaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_incrementoVentaFocusLost

    private void gananciaIndividualFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gananciaIndividualFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_gananciaIndividualFocusGained

    private void gananciaIndividualFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gananciaIndividualFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_gananciaIndividualFocusLost

    private void gananciaIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gananciaIndividualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gananciaIndividualActionPerformed

    private void gananciaIndividualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gananciaIndividualKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_gananciaIndividualKeyPressed

    private void incrementoVentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incrementoVentaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_incrementoVentaMousePressed

    private void incrementoVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incrementoVentaMouseEntered

    }//GEN-LAST:event_incrementoVentaMouseEntered

    private void incrementoVentaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_incrementoVentaStateChanged
        // TODO add your handling code here:
        controller.despliegaCuentas();
    }//GEN-LAST:event_incrementoVentaStateChanged

    private void gananciaTotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gananciaTotalFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_gananciaTotalFocusGained

    private void gananciaTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gananciaTotalFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_gananciaTotalFocusLost

    private void gananciaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gananciaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gananciaTotalActionPerformed

    private void gananciaTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gananciaTotalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_gananciaTotalKeyPressed

    private void inversionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inversionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_inversionFocusGained

    private void inversionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inversionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_inversionFocusLost

    private void inversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inversionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inversionActionPerformed

    private void inversionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inversionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inversionKeyPressed

    private void idProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProveedorActionPerformed

    private void idProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idProveedorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProveedorKeyPressed

    private void idProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProductoActionPerformed
        // TODO add your handling code here:
        controller.identificaInfo(panelImagen);
    }//GEN-LAST:event_idProductoActionPerformed

    private void idProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idProductoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProductoKeyPressed

    private void imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenActionPerformed
        // TODO add your handling code here:
        Controller.ControllerImagenes image = new Controller.ControllerImagenes();
        image.buscaImagen(panelImagen,imagen);
        controller.setRutaImagen(image.getRuta());
    }//GEN-LAST:event_imagenActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        controller.eliminaCategoria(labelStatus);
    }//GEN-LAST:event_eliminarActionPerformed

    
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JTextField cantidad01;
    private javax.swing.JTextField cantidad02;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField gananciaIndividual;
    private javax.swing.JTextField gananciaTotal;
    private javax.swing.JComboBox idCategoria;
    private javax.swing.JComboBox idProducto;
    private javax.swing.JComboBox idProveedor;
    private javax.swing.JButton imagen;
    private javax.swing.JSpinner incrementoVenta;
    private javax.swing.JTextField inversion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelNota;
    private javax.swing.JLabel labelRuta;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelStatus02;
    private javax.swing.JSpinner maxStock;
    private javax.swing.JSpinner minStock;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JTextField precioCompra01;
    private javax.swing.JTextField precioCompra02;
    private javax.swing.JTextField precioVenta01;
    private javax.swing.JComboBox tipoUnidad;
    private javax.swing.JTextField unidadExistencia;
    // End of variables declaration//GEN-END:variables
}
