/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.ControllerClockPanel;
import Controller.ControllerDatePanel;
import Model.ModelEmpresa;
import Model.ModelUsuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author Jesus
 */
public class ViewAdminsitrador extends javax.swing.JFrame {
    ModelEmpresa modelEmpresa;
    ModelUsuario modelUsuario;
    ControllerClockPanel hiloHora;
    public static int idUsuario;
    /**
     * Creates new form principal
     * @param modelEmpresa
     * @param modelUsuario
     */
    public ViewAdminsitrador(ModelEmpresa modelEmpresa, ModelUsuario modelUsuario) {
        this.modelEmpresa = modelEmpresa;
        this.modelUsuario = modelUsuario;
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/Logo.png"));
        setIconImage(icon);
        initClock();
        initFecha();
        configIniciales();
        addPanel(jPanelCentral,new JPanel());
    }
    
    private void initFecha(){
       jLabelFecha.setText(ControllerDatePanel.getFecha());
    }
    
    private void initClock(){
        hiloHora = new ControllerClockPanel(jLabelHora);
        Thread clock=new Thread(hiloHora);
        clock.start();
    }
    
    private void configIniciales()
    {
        jLabelHora1.setText(modelEmpresa.getNombre());
        usuario.setText(modelUsuario.getNombre()+" "+modelUsuario.getaPaterno()+" "+modelUsuario.getaMaterno());
        Dimension dim = super.getToolkit().getScreenSize(); 
        super.setBackground(new Color(44,62,80));
        super.setSize(dim); 
        super.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }
    
    private void addPanel(JPanel panelBase,JPanel add)
    {
        panelBase.setLayout(new GridBagLayout());
        panelBase.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        panelBase.setVisible(true);
        panelBase.add(add);
        panelBase.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        BCerrar = new javax.swing.JButton();
        BMin = new javax.swing.JButton();
        jLabelFecha = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jPanelCentral = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelDatUsu = new javax.swing.JPanel();
        Titulo01 = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jLabelHora1 = new javax.swing.JLabel();
        jPanelEncabezado = new javax.swing.JPanel();
        iniciar1 = new javax.swing.JButton();
        iniciar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelTitulo.setBackground(new java.awt.Color(245, 246, 247));
        panelTitulo.setForeground(new java.awt.Color(0, 51, 51));

        BCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IconClose.png"))); // NOI18N
        BCerrar.setToolTipText("Salir");
        BCerrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BCerrar.setBorderPainted(false);
        BCerrar.setContentAreaFilled(false);
        BCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCerrarActionPerformed(evt);
            }
        });

        BMin.setBackground(new java.awt.Color(255, 255, 255));
        BMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/minim.png"))); // NOI18N
        BMin.setToolTipText("Minimizar");
        BMin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BMin.setBorderPainted(false);
        BMin.setContentAreaFilled(false);
        BMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMinActionPerformed(evt);
            }
        });

        jLabelFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(51, 51, 51));
        jLabelFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFecha.setText("Fecha");

        jLabelHora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(51, 51, 51));
        jLabelHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHora.setText("Clock");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BCerrar))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addComponent(BMin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelCentral.setBackground(new java.awt.Color(204, 204, 204));
        jPanelCentral.setForeground(new java.awt.Color(204, 204, 204));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo.png"))); // NOI18N

        jPanelDatUsu.setBackground(new java.awt.Color(51, 51, 51));
        jPanelDatUsu.setForeground(new java.awt.Color(204, 204, 204));

        Titulo01.setBackground(new java.awt.Color(255, 255, 255));
        Titulo01.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Titulo01.setForeground(new java.awt.Color(255, 255, 255));
        Titulo01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo01.setText("Bienvenido");

        usuario.setBackground(new java.awt.Color(255, 255, 255));
        usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario.setText("Jesus Salazar");

        javax.swing.GroupLayout jPanelDatUsuLayout = new javax.swing.GroupLayout(jPanelDatUsu);
        jPanelDatUsu.setLayout(jPanelDatUsuLayout);
        jPanelDatUsuLayout.setHorizontalGroup(
            jPanelDatUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo01, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelDatUsuLayout.setVerticalGroup(
            jPanelDatUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatUsuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelHora1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelHora1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHora1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHora1.setText("Nombre");

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanelDatUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabelHora1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelHora1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEncabezado.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEncabezado.setForeground(new java.awt.Color(205, 212, 205));
        jPanelEncabezado.setToolTipText("");

        iniciar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iniciar1.setForeground(new java.awt.Color(51, 51, 51));
        iniciar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home.png"))); // NOI18N
        iniciar1.setText("Inicio");
        iniciar1.setContentAreaFilled(false);
        iniciar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciar1.setSelected(true);
        iniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar1ActionPerformed(evt);
            }
        });

        iniciar2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iniciar2.setForeground(new java.awt.Color(51, 51, 51));
        iniciar2.setText("Productos");
        iniciar2.setContentAreaFilled(false);
        iniciar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciar2.setSelected(true);
        iniciar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEncabezadoLayout = new javax.swing.GroupLayout(jPanelEncabezado);
        jPanelEncabezado.setLayout(jPanelEncabezadoLayout);
        jPanelEncabezadoLayout.setHorizontalGroup(
            jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iniciar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iniciar2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEncabezadoLayout.setVerticalGroup(
            jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniciar2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCentral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BCerrarActionPerformed

    private void BMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMinActionPerformed
        // TODO add your handling code here:
        setExtendedState(ViewAdminsitrador.CROSSHAIR_CURSOR); 
    }//GEN-LAST:event_BMinActionPerformed

    private void iniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar1ActionPerformed
    
    }//GEN-LAST:event_iniciar1ActionPerformed

    private void iniciar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciar2ActionPerformed

    public void agregaJPanel(JPanel panelBase, JPanel panelAdd)
    {
        panelBase.removeAll();
        panelBase.add(panelAdd,LEFT_ALIGNMENT);
        panelBase.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCerrar;
    private javax.swing.JButton BMin;
    private javax.swing.JLabel Titulo01;
    private javax.swing.JButton iniciar;
    private javax.swing.JButton iniciar1;
    private javax.swing.JButton iniciar2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelHora1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelDatUsu;
    private javax.swing.JPanel jPanelEncabezado;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
