--- EMPRESA ---
INSERT INTO EMPRESA (IDEMPRESA,NOMBRE,RAZONSOCIAL,RFC,CAPITALINICIAL,FLUJOEFECTIVO,DOMICILIO) 
			 VALUES (1,'SAPITO','S.A. DE C.V.','SAPITO235412W','10000','0','AV. BENITO JUAREZ NO. 103');
--- PROVEEDOR ---
INSERT INTO PROVEEDOR (NOMBRE,EMPRESA_IDEMPRESA) VALUES ('RAMON',1);
--- DATOS COMPRA ---
INSERT INTO DATOSCOMPRA (TOTALESPERADO,TOTALRECIBIDO) VALUES (2000,2000);
--- ORDEN COMPRA --
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (2,'12-01-14',2300,1,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (3,'12-03-14',2300,1,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (4,'14-01-14',2300,0,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (5,'12-03-14',2300,1,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (6,'16-04-11',2300,0,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (7,'12-03-14',2300,1,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (8,'22-04-14',2300,0,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (9,'12-07-14',2300,1,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (10,'12-04-012',2300,0,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (11,'14-08-014',2300,1,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (12,'11-03-011',2300,0,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (13,'12-08-013',2300,1,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (14,'18-01-014',2300,0,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (15,'28-08-014',2300,1,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (16,'12-01-012',2300,1,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (17,'12-03-014',2300,0,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (18,'01-07-014',2300,0,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (19,'12-01-011',2300,0,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (20,'02-08-014',2300,1,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (21,'12-07-014',2300,0,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (22,'03-01-014',2300,1,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (23,'24-08-012',2300,1,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (24,'02-01-014',2300,1,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (25,'12-08-014',2300,0,1,1);
INSERT INTO ORDENCOMPRA (IDORDENCOMPRA,FECHACOMPRA,TOTAL,ACTIVOFIJO,APROBADA,PROVEEDOR_IDPROVEEDOR) VALUES (26,'11-01-013',2300,1,1,1);
-
--- CATEGORIA ---
INSERT INTO (DESCRIPCION) VALUES ('VINOS Y LICORES');
INSERT INTO (DESCRIPCION) VALUES ('ROPA');
INSERT INTO (DESCRIPCION) VALUES ('ELECTRODOMESTICOS');
--- ACTIVO FIJO ---
INSERT INTO (VALOR_ACTUAL) VALUES (1234);
INSERT INTO (VALOR_ACTUAL) VALUES (5678);
INSERT INTO (VALOR_ACTUAL) VALUES (9012);
--- PRODCUTOS
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,1);
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,1);
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,1);
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,1);
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,1);
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,1);
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,1);			  			  			  			  			  			  			  
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,1);
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,1);
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,NULL);
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,NULL);
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,NULL);
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,NULL);
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,NULL);
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,NULL);
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,NULL);
INSERT INTO PRODUCTO (MARCA,NOMBRE,EMPRESA_IDEMPRESA,CATEGORIA_IDCATEGORIA,ACTIVOFIJO_IDACTIVOFIJO) VALUES ('NESTLE','LECHE ALPURA',1,1,NULL);
--- UNIDAD ---
