/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerValidation;
import Controller.ControllerViewEmpresa;
import Model.ModelEmpresa;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Jesus
 */
public class ViewCaptInfoBussines extends javax.swing.JPanel {
    JLabel labelStatus;
    Thread hilo;
    ModelEmpresa modelEmpresa;
    ControllerValidation validation;
    ControllerViewEmpresa controller;
    /**
     * Creates new form ViewCaptInfoBussines
     * @param labelStatus
     * @param hilo
     * @param modelEmpresa
     */
    public ViewCaptInfoBussines(JLabel labelStatus, Thread hilo,ModelEmpresa modelEmpresa) {
        validation = new ControllerValidation();
        this.labelStatus = labelStatus;
        this.hilo = hilo;
        this.modelEmpresa = modelEmpresa;
        initComponents();
        validation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        house = new javax.swing.JLabel();
        nameBussines = new javax.swing.JTextField();
        rfc = new javax.swing.JTextField();
        contacs = new javax.swing.JLabel();
        street = new javax.swing.JTextField();
        codePost = new javax.swing.JTextField();
        contacs2 = new javax.swing.JLabel();
        numInt = new javax.swing.JTextField();
        numExt = new javax.swing.JTextField();
        col = new javax.swing.JTextField();
        web1 = new javax.swing.JLabel();
        pagWeb = new javax.swing.JTextField();
        mail = new javax.swing.JLabel();
        eMail = new javax.swing.JTextField();
        labelNota = new javax.swing.JLabel();
        next = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 246, 247));

        jPanel1.setBackground(new java.awt.Color(245, 246, 247));

        house.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home.png"))); // NOI18N

        nameBussines.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameBussines.setForeground(new java.awt.Color(180, 180, 180));
        nameBussines.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameBussines.setText("Nombre de la empresa (*)");
        nameBussines.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameBussinesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameBussinesFocusLost(evt);
            }
        });
        nameBussines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBussinesActionPerformed(evt);
            }
        });
        nameBussines.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameBussinesKeyPressed(evt);
            }
        });

        rfc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rfc.setForeground(new java.awt.Color(180, 180, 180));
        rfc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        rfc.setText("R.F.C. (*)");
        rfc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rfcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rfcFocusLost(evt);
            }
        });
        rfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfcActionPerformed(evt);
            }
        });
        rfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rfcKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rfcKeyTyped(evt);
            }
        });

        contacs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/contacts.png"))); // NOI18N

        street.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        street.setForeground(new java.awt.Color(180, 180, 180));
        street.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        street.setText("Calle");
        street.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                streetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                streetFocusLost(evt);
            }
        });
        street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetActionPerformed(evt);
            }
        });
        street.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                streetKeyPressed(evt);
            }
        });

        codePost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        codePost.setForeground(new java.awt.Color(180, 180, 180));
        codePost.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        codePost.setText("C.P.");
        codePost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codePostFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codePostFocusLost(evt);
            }
        });
        codePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codePostActionPerformed(evt);
            }
        });
        codePost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codePostKeyPressed(evt);
            }
        });

        contacs2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/contacts.png"))); // NOI18N

        numInt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numInt.setForeground(new java.awt.Color(180, 180, 180));
        numInt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        numInt.setText("No. Int.");
        numInt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numIntFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numIntFocusLost(evt);
            }
        });
        numInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numIntActionPerformed(evt);
            }
        });
        numInt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numIntKeyPressed(evt);
            }
        });

        numExt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numExt.setForeground(new java.awt.Color(180, 180, 180));
        numExt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        numExt.setText("No. Ext.");
        numExt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numExtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numExtFocusLost(evt);
            }
        });
        numExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numExtActionPerformed(evt);
            }
        });
        numExt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numExtKeyPressed(evt);
            }
        });

        col.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        col.setForeground(new java.awt.Color(180, 180, 180));
        col.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        col.setText("Colonia");
        col.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                colFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                colFocusLost(evt);
            }
        });
        col.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colActionPerformed(evt);
            }
        });
        col.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                colKeyPressed(evt);
            }
        });

        web1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clipboard.png"))); // NOI18N

        pagWeb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pagWeb.setForeground(new java.awt.Color(180, 180, 180));
        pagWeb.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pagWeb.setText("Página Web");
        pagWeb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pagWebFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pagWebFocusLost(evt);
            }
        });
        pagWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagWebActionPerformed(evt);
            }
        });
        pagWeb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pagWebKeyPressed(evt);
            }
        });

        mail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mail.png"))); // NOI18N

        eMail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eMail.setForeground(new java.awt.Color(180, 180, 180));
        eMail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        eMail.setText("E-mail");
        eMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                eMailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                eMailFocusLost(evt);
            }
        });
        eMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMailActionPerformed(evt);
            }
        });
        eMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eMailKeyPressed(evt);
            }
        });

        labelNota.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelNota.setForeground(new java.awt.Color(153, 0, 0));
        labelNota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNota.setText("Nota: (*) Campos obligatorios");

        next.setFont(new java.awt.Font("CordiaUPC", 0, 24)); // NOI18N
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chevron-right.png"))); // NOI18N
        next.setText("Siguiente");
        next.setContentAreaFilled(false);
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.setSelected(true);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(next))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(eMail, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(contacs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(codePost, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(contacs2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numInt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numExt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(col, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(house)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameBussines, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rfc, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(web1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameBussines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(house, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contacs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codePost)
                    .addComponent(street))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(col, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(contacs2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(web1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eMail)
                    .addComponent(mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNota, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void validation(){
        ArrayList components = new ArrayList<>();
        components.add(nameBussines);
        components.add(rfc);
        components.add(street);
        components.add(numInt);
        components.add(numExt);
        components.add(col);
        components.add(codePost);
        components.add(pagWeb);
        components.add(eMail);
        controller = new ControllerViewEmpresa(components);
        controller.validations();
    }
    
    private void streetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetFocusGained
        validation.placeHolder(true,street,"Calle");
    }//GEN-LAST:event_streetFocusGained

    private void streetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetFocusLost
        validation.placeHolder(false,street,"Calle");  
    }//GEN-LAST:event_streetFocusLost

    private void streetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetActionPerformed

    private void streetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_streetKeyPressed
        if(evt.getKeyChar()==10)
            next();
    }//GEN-LAST:event_streetKeyPressed

    private void numIntFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numIntFocusGained
        validation.placeHolder(true,numInt,"No. Int.");
    }//GEN-LAST:event_numIntFocusGained

    private void numIntFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numIntFocusLost
        validation.placeHolder(false,numInt,"No. Int.");
    }//GEN-LAST:event_numIntFocusLost

    private void numIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numIntActionPerformed

    private void numIntKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numIntKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10)
            next();
    }//GEN-LAST:event_numIntKeyPressed

    private void numExtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numExtFocusGained
       validation.placeHolder(true,numExt,"No. Ext.");
    }//GEN-LAST:event_numExtFocusGained

    private void numExtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numExtFocusLost
        validation.placeHolder(false,numExt,"No. Ext.");
    }//GEN-LAST:event_numExtFocusLost

    private void numExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numExtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numExtActionPerformed

    private void numExtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numExtKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyChar()==10)
            next();
    }//GEN-LAST:event_numExtKeyPressed

    private void colFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_colFocusGained
        validation.placeHolder(true,col,"Colonia");
    }//GEN-LAST:event_colFocusGained

    private void colFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_colFocusLost
        validation.placeHolder(false,col,"Colonia");
    }//GEN-LAST:event_colFocusLost

    private void colActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colActionPerformed

    private void colKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyChar()==10)
            next();
    }//GEN-LAST:event_colKeyPressed

    private void codePostFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codePostFocusGained
        validation.placeHolder(true,codePost,"C.P.");
    }//GEN-LAST:event_codePostFocusGained

    private void codePostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codePostFocusLost
        validation.placeHolder(false,codePost,"C.P.");
    }//GEN-LAST:event_codePostFocusLost

    private void codePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codePostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codePostActionPerformed

    private void codePostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codePostKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyChar()==10)
            next();
    }//GEN-LAST:event_codePostKeyPressed

    private void pagWebFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pagWebFocusGained
        validation.placeHolder(true,pagWeb,"Página Web");
    }//GEN-LAST:event_pagWebFocusGained

    private void pagWebFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pagWebFocusLost
        validation.placeHolder(false,pagWeb,"Página Web");
    }//GEN-LAST:event_pagWebFocusLost

    private void pagWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagWebActionPerformed

    private void pagWebKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pagWebKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyChar()==10)
            next();
    }//GEN-LAST:event_pagWebKeyPressed

    private void eMailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eMailFocusGained
        validation.placeHolder(true,eMail,"E-mail");
    }//GEN-LAST:event_eMailFocusGained

    private void eMailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eMailFocusLost
        validation.placeHolder(false,eMail,"E-mail");
    }//GEN-LAST:event_eMailFocusLost

    private void eMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMailActionPerformed

    private void eMailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eMailKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyChar()==10)
            next();
    }//GEN-LAST:event_eMailKeyPressed

    private void nameBussinesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameBussinesFocusGained
        validation.placeHolder(true,nameBussines,"Nombre de la empresa (*)");
    }//GEN-LAST:event_nameBussinesFocusGained

    private void nameBussinesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameBussinesFocusLost
        validation.placeHolder(false ,nameBussines,"Nombre de la empresa (*)");
    }//GEN-LAST:event_nameBussinesFocusLost

    private void nameBussinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBussinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameBussinesActionPerformed

    private void nameBussinesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameBussinesKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyChar()==10)
            next();
    }//GEN-LAST:event_nameBussinesKeyPressed

    private void rfcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rfcFocusGained
        validation.placeHolder(true,rfc,"R.F.C. (*)");
    }//GEN-LAST:event_rfcFocusGained

    private void rfcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rfcFocusLost
        validation.placeHolder(false,rfc,"R.F.C. (*)");
    }//GEN-LAST:event_rfcFocusLost

    private void rfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfcActionPerformed

    private void rfcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rfcKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyChar()==10)
            next();
    }//GEN-LAST:event_rfcKeyPressed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_nextActionPerformed

    private void next(){
        controller.next(labelStatus,hilo,modelEmpresa);
    }
    
    private void rfcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rfcKeyTyped

    }//GEN-LAST:event_rfcKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codePost;
    private javax.swing.JTextField col;
    private javax.swing.JLabel contacs;
    private javax.swing.JLabel contacs2;
    private javax.swing.JTextField eMail;
    private javax.swing.JLabel house;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNota;
    private javax.swing.JLabel mail;
    private javax.swing.JTextField nameBussines;
    private javax.swing.JButton next;
    private javax.swing.JTextField numExt;
    private javax.swing.JTextField numInt;
    private javax.swing.JTextField pagWeb;
    private javax.swing.JTextField rfc;
    private javax.swing.JTextField street;
    private javax.swing.JLabel web1;
    // End of variables declaration//GEN-END:variables
}
